stages:
  - build
  - deploy

variables:
  RUNNER_TAG: "If-common"
  RUNNER_SHELL_TAG: "If-shell-common"
  IMAGE_NAME: "registry.gitlab.com/aleksturbo/$CI_PROJECT_NAME:${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}"
  LATEST_IMAGE_NAME: "registry.gitlab.com/aleksturbo/$CI_PROJECT_NAME"

workflow:
  rules:
    - if: '$CI_COMMIT_REF_NAME == "develop"'
      variables:
        RUNNER_TAG: "lf-runner1"
        RUNNER_SHELL_TAG: "lf-runner-shell1"
    - if: '$CI_COMMIT_REF_NAME == "main"'
      variables:
        RUNNER_TAG: "lf-runner2"
        RUNNER_SHELL_TAG: "lf-runner-shell2"

build_images:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  script:
    - echo $CI_REGISTRY
    - echo $CI_REGISTRY_USER
    - echo $CI_REGISTRY_PASSWORD
    - echo $CI_PROJECT_NAME
    - echo $MY_VAR
    - echo $CI_COMMIT_SHORT_SHA
    - echo $CI_COMMIT_REF_NAME
    - echo $CI_COMMIT_TAG
    - pwd
    - mkdir -p /kaniko/.docker
    - ls -la
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --cache --cache-repo $CI_REGISTRY_IMAGE --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $IMAGE_NAME
    - /kaniko/executor --cache --cache-repo $CI_REGISTRY_IMAGE --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $LATEST_IMAGE_NAME
  tags:
    - $RUNNER_TAG

deploy:
  stage: deploy
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker pull $IMAGE_NAME
    - docker stop my.app || true
    - docker rm my.app || true
    - docker run -d -p 5000:5000 --name my.app $IMAGE_NAME
  tags:
    - $RUNNER_SHELL_TAG 
  environment:
    name: $CI_COMMIT_REF_NAME
  only:
    - develop
    - main
