stages:
  - build
  - deploy

variables:
  RUNNER_TAG: "If-common"
  RUNNER_SHELL_TAG: "If-shell-common"
  IMAGE_NAME: "registry.gitlab.com/aleksturbo/$CI_PROJECT_NAME:${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}"
  LATEST_IMAGE_NAME: "registry.gitlab.com/aleksturbo/$CI_PROJECT_NAME"
  ENVIRONMENT:
    value: "N/A"
    options:
    - "N/A"
    - "STAGE"
    - "PRODUCTION"
    description: "Deployment environment"

.stage_server:
  &stage_server
    RUNNER_SHELL_TAG: "lf-runner-shell1"
    WEB_NODE: "192.168.153.113"
    DB_NODE: "192.168.153.113"

.production_server:
  &production_server
    RUNNER_SHELL_TAG: "lf-runner-shell2"
    WEB_NODE: "192.168.153.112"
    DB_NODE: "192.168.153.112"

workflow:
  rules:
    - if: '$CI_COMMIT_REF_NAME == "develop"'
      variables:
        RUNNER_TAG: "lf-runner1"
        RUNNER_SHELL_TAG: "lf-runner-shell1"
    - if: '$CI_COMMIT_REF_NAME == "main"'
      variables:
        RUNNER_TAG: "lf-runner2"
        RUNNER_SHELL_TAG: "lf-runner-shell2"
    - if: '$ENVIRONMENT == "STAGE"'
      variables:
        RUNNER_SHELL_TAG: "lf-runner-shell1"
    - if: '$ENVIRONMENT == "PRODUCTION"'
      variables:
        RUNNER_SHELL_TAG: "lf-runner-shell2"
        
build_images:
  stage: build
  when: manual
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  script:
    - mkdir docs
    - echo $CI_REGISTRY >> docs/build.log
    - echo $CI_REGISTRY_USER >> docs/build.log
    - echo $CI_REGISTRY_PASSWORD >> docs/build.log
    - echo $CI_PROJECT_NAME >> docs/build.log
    - echo $MY_VAR > docs/build.log
    - echo $CI_COMMIT_SHORT_SHA >> docs/build.log
    - echo $CI_COMMIT_REF_NAME >> docs/build.log
    - echo $CI_COMMIT_TAG >> docs/build.log
    - pwd >> docs/build.log
    - mkdir -p /kaniko/.docker >> docs/build.log
    - echo "Build completed" >> docs/build.txt
    - ls -la >> docs/build.log
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json >> docs/build.log
    - /kaniko/executor --cache --cache-repo $CI_REGISTRY_IMAGE --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $IMAGE_NAME >> docs/build.log
    - /kaniko/executor --cache --cache-repo $CI_REGISTRY_IMAGE --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $LATEST_IMAGE_NAME >> docs/build.log
    # - curl --location --output artifacts.zip "https://gitlab.com/api/v4/projects/1/jobs/artifacts/main/download?job=test&job_token=$CI_JOB_TOKEN"
  tags:
    - $RUNNER_TAG
  variables:
    FF_ENABLE_JOB_CLEANUP: "false"
  artifacts:
    paths:
      - docs/
    expire_in: 1 week
    reports:
      dotenv: build.env

deploy:
  stage: deploy
  when: manual
  script:
    - echo $ENVIRONMENT
    - echo "build & deploy here"
    - echo $RUNNER_SHELL_TAG
    - echo $RUNNER_SHELL2_TAG
    - echo $WEB_NODE
    - cat docs/build.txt
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker pull $IMAGE_NAME
    - docker stop my.app || true
    - docker rm my.app || true
    - docker run -d -p 5000:5000 --name my.app $IMAGE_NAME
  rules:
    - if: '$ENVIRONMENT == "STAGE"'
      variables:
        <<: *stage_server
    - if: '$ENVIRONMENT == "PRODUCTION"'
      variables:
        <<: *production_server
  dependencies:
    - build_images
  tags:
    - $RUNNER_SHELL_TAG
  environment:
    name: $CI_COMMIT_REF_NAME
