stages:
  - build

build_images:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  script:
    - echo $CI_REGISTRY
    - echo $CI_REGISTRY_USER
    - echo $CI_REGISTRY_PASSWORD
    - echo $CI_PROJECT_NAME
    - echo $MY_VAR
    - echo $CI_COMMIT_SHORT_SHA
    - echo $CI_COMMIT_REF_NAME
    - echo $CI_COMMIT_TAG
    - pwd
    - ls -la
    # - exit 1
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $IMAGE_NAME
  tags:
    - $CI_COMMIT_REF_NAME
  rules:
    - if: '$CI_COMMIT_REF_NAME == "develop"'
      variables:
        IMAGE_NAME: "registry.gitlab.com/aleksturbo/$CI_PROJECT_NAME:dev_$CI_COMMIT_SHORT_SHA"
    - if: '$CI_COMMIT_REF_NAME == "main"'
      variables:
        IMAGE_NAME: "registry.gitlab.com/aleksturbo/$CI_PROJECT_NAME:prod_$CI_COMMIT_SHORT_SHA"